# BEGIN_KITTY_THEME
# Everforest Dark Hard
include current-theme.conf
# END_KITTY_THEME
#

font_family Iosevka
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 22
modify_font cell_height 120%
adjust_line_height  112%
adjust_column_width 100%

cursor_shape beam

window_margin_width 8
window_padding_width 0
remember_window_size  no
initial_window_width  200c
initial_window_height 50c

confirm_os_window_close 0
macos_quit_when_last_window_closed yes
enable_audio_bell no
copy_on_select yes

# copies selection if present, else sends the interrupt through
map ctrl+c copy_or_interrupt
